# Sets the features for the live plotter to start with
# Each row is one chart
- ['Angle', 'None', 'None']
- ['Target Position', 'Position', 'None']
- ['Q', 'None', 'None']
- ['total_stage_cost', 'None', 'None']
- ['total_stage_cost', 'None', 'None']
