library: 'TF'  # TF or Pytorch
modeling:
  NET_NAME: 'Dense-16H1-16H2'
paths:
  # PATH HAS TO END WITH A SOLIDUS ("/") CHARACTER
  path_to_experiment: 'CPS-17-02-2023-UpDown-Imitation/'
  PATH_TO_EXPERIMENT_FOLDERS: './SI_Toolkit_ASF/Experiments/'  # Path where the experiments data is stored

training_default:
  # For training closed loop dynamics model:
#  control_inputs: ['Q']
#  state_inputs: ['angle_sin', 'angle_cos', 'angleD', 'position', 'positionD']
#  setpoint_inputs: []  # Can be only 'target_position' or empty for CartPole
#  outputs: ['angle_sin', 'angle_cos', 'angleD', 'position', 'positionD']
  #  outputs: ['D_angle_sin', 'D_angle_cos', 'D_angleD', 'D_position', 'D_positionD'] # Don't forget to change SHIFT_LABELS to 0
  translation_invariant_variables: []
  # For training open loop dynamics model:
  # inputs = ['position', 'positionD', 'angle_sin', 'angle_cos', 'angleD']
  # outputs = inputs_list
  # For training of a network imitating MPC:
  control_inputs: []
  setpoint_inputs: ['target_position', 'target_equilibrium']  # Can be only 'target_position' or empty for CartPole
  state_inputs: ['position', 'positionD', 'angle_cos', 'angle_sin', 'angleD']
  outputs:  ['Q']
  EPOCHS: 20
  BATCH_SIZE: 16
  SEED: 1873
  LR: 1.0e-3
  WASH_OUT_LEN: 0
  POST_WASH_OUT_LEN: 1
  ON_FLY_DATA_GENERATION: False
  NORMALIZE: True
  SHIFT_LABELS: 0  # for k, as a label to row i is taken row i+k
  USE_NNI: False  # Decide if you want to use NNI package
  CONSTRUCT_NETWORK: 'with cells'  # Matters only for Pytorch; 'with cells' or 'with modules'

